version: '3.8'

services:
  www:
    build: . 
    container_name: pizzashop-backend
    image: oven/bun
    ports:
      - '8080:8080'
    env_file:
      - .env
    volumes: 
      - "./:/home/bun/app"
    depends_on:
      - postgres

  postgres:
    container_name: pizzashop-db
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pizzashop
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: